version: "3"
services:
  golang:
    build: .
    container_name: "golang"
    tty: true
    volumes:
      - ./:/app/
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
